"""Central configuration for the RAG pipeline.

Every tunable lives here and is sourced from environment variables (loaded from
a local ``.env`` if present). Both the CLI and the Streamlit app build their
``Settings`` from :meth:`Settings.from_env`, so they always agree on where the
index lives, which models to use, and how documents are chunked.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, fields
from pathlib import Path

from dotenv import load_dotenv

# Load .env once, at import time, so `os.environ` is populated before any
# Settings are built. `override=False` means a real environment variable always
# wins over the .env file.
load_dotenv(override=False)

# Repository root = two levels up from this file (rag_pipeline/config.py).
_ROOT = Path(__file__).resolve().parent.parent


def _env_path(name: str, default: Path) -> Path:
    value = os.getenv(name)
    return Path(value).expanduser().resolve() if value else default


def _env_int(name: str, default: int) -> int:
    value = os.getenv(name)
    return int(value) if value else default


def _env_str(name: str, default: str) -> str:
    # A set-but-empty var (e.g. `CHAT_MODEL=`) falls back to the default, so
    # string settings behave like the int/path helpers rather than passing ""
    # straight through to the model/store.
    value = os.getenv(name)
    return value if value else default


@dataclass(frozen=True)
class Settings:
    """Immutable bundle of pipeline configuration."""

    # Where source documents (.md/.txt/.pdf) are read from during ingest.
    data_dir: Path = _ROOT / "data"

    # Where Chroma persists the embedded index. Regenerated by `rag ingest`.
    persist_dir: Path = _ROOT / "chroma_db"
    collection_name: str = "rag_docs"

    # Local sentence-transformers model. Runs on-device, no API key needed.
    # all-MiniLM-L6-v2 -> 384-dim vectors; small, fast, and solid for retrieval.
    embedding_model: str = "sentence-transformers/all-MiniLM-L6-v2"

    # Generation model. Haiku 4.5 is a fast, low-cost default for demos;
    # override via CHAT_MODEL (e.g. claude-opus-4-8) for higher-quality answers.
    chat_model: str = "claude-haiku-4-5"
    max_tokens: int = 1024

    # Splitter: 1000-char chunks with 200-char (20%) overlap keeps enough
    # context per chunk while preserving continuity across chunk boundaries.
    chunk_size: int = 1000
    chunk_overlap: int = 200

    # Number of chunks retrieved per question and stuffed into the prompt.
    retrieval_k: int = 4

    @classmethod
    def from_env(cls) -> Settings:
        """Build settings, letting environment variables override defaults."""
        return cls(
            data_dir=_env_path("DATA_DIR", cls.data_dir),
            persist_dir=_env_path("PERSIST_DIR", cls.persist_dir),
            collection_name=_env_str("COLLECTION_NAME", cls.collection_name),
            embedding_model=_env_str("EMBEDDING_MODEL", cls.embedding_model),
            chat_model=_env_str("CHAT_MODEL", cls.chat_model),
            max_tokens=_env_int("MAX_TOKENS", cls.max_tokens),
            chunk_size=_env_int("CHUNK_SIZE", cls.chunk_size),
            chunk_overlap=_env_int("CHUNK_OVERLAP", cls.chunk_overlap),
            retrieval_k=_env_int("RETRIEVAL_K", cls.retrieval_k),
        )


# Every field's environment variable, derived rather than restated. Tests clear
# these before asserting on defaults, and a hand-kept list would drift silently:
# this module calls load_dotenv() at import time, so a name missing from that
# list is answered by the developer's own .env and its default stops being
# tested. Deriving costs one line and makes the drift inexpressible.
ENV_VARS = tuple(field.name.upper() for field in fields(Settings))
